@startuml

title the component model

class AemContext {
    wcmmode: string;
    cqHidden?: boolean;
    path: string;
    resource: Resource;
    registry: RootComponentRegistry;
}

class AemComponent {

    getResource(): Resource
    getPath(): string
    getResourceType(): string
    getWcmmode(): string
    isCqHidden(): boolean
    setAllEditableVisible(path: string, visible: boolean)
}

AemComponent -> AemContext : context

class Resource {
    "sling:resourceType": string;
}

class ResourceProps<R extends Resource> {
    resource?: C;
    component?: string;
    path: string;
    root?: boolean;
    wcmmode?: string;
    cqHidden?: boolean;

}

ResourceProps -> Resource : resource

class ResourceComponent<R extends Resource> extends AemComponent{
    renderBody()
}

note left of ResourceComponent
ResourceComponent has type parameters:
- Resource
- ResourceProps
- State
end note


ResourceComponent -> ResourceProps : props


class MyComponent<MyResource> extends ResourceComponent {
    getResource():MyResource
}

class MyResource extends Resource {
}

MyComponent --> ResourceProps : props

MyComponent .> MyResource



@enduml